### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-scripts#23]
@matze How about ufo-tools? It fits the nonexecutable parts better. And if you don't like `unfoog` we can just call it the boring `src`.

**Comment by matze** [comment]
Repo name is good, `src` not so much since a) it will be installed globally and 2) the imports would look too weird.

**Comment by tfarago** [comment]
Regarding the package name, the repo name `ufo-tools` shorthands for `ufo-t`, nicer `ufot`, reverse: `tofu` :smile: 
Buuuuut, yeah...

**Comment by tfarago** [comment]
Or the boring obvious choice `ufotools`...

**Comment by matze** [comment]
I could get used to tofu. So yeah, let's do that once #22 is in.
